# Generated by Django 5.1.6 on 2025-03-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_category_description_alter_category_parent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="publication_date",
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
