# Generated by Django 5.1.6 on 2025-03-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_article_publication_date_alter_article_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedImage",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("image", models.ImageField(upload_to="generated_images/")),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
