# Generated by Django 5.1.6 on 2025-03-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_generatedimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="generatedimage",
            name="image",
        ),
        migrations.AddField(
            model_name="generatedimage",
            name="image_url",
            field=models.URLField(default="https://example.com/default_image.png"),
        ),
    ]
