# Generated by Django 5.1.6 on 2025-03-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_remove_generatedimage_image_generatedimage_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generatedimage",
            name="image_url",
            field=models.URLField(
                default="https://github.com/d-perreaux/OCR_initiation_machine_learning/blob/main/exo_01_regression_lineaire_simple/toto.png?raw=true"
            ),
        ),
    ]
