# Generated by Django 5.1.6 on 2025-03-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_generatedimage_image_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="ElectionDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
            ],
        ),
    ]
