# Generated by Django 5.2 on 2025-05-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exploration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultatelection',
            name='desir_changement_avec_centre',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultatelection',
            name='desir_changement_centre_extremes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultatelection',
            name='desir_changement_sans_centre',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultatelection',
            name='encodage_avec_centre_gagnant',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultatelection',
            name='encodage_avec_centre_gagnant_precedent',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultatelection',
            name='encodage_centre_extremes_gagnant',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultatelection',
            name='encodage_centre_extremes_gagnant_precedent',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultatelection',
            name='encodage_sans_centre_gagnant',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultatelection',
            name='encodage_sans_centre_gagnant_precedent',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultatelection',
            name='gagnant',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultatelection',
            name='gagnant_precedent',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultatelection',
            name='instabilite_avec_centre',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultatelection',
            name='instabilite_centre_extremes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultatelection',
            name='instabilite_sans_centre',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultatelection',
            name='poids_nuance_avec_centre',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultatelection',
            name='poids_nuance_centre_extremes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultatelection',
            name='poids_nuance_sans_centre',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultatelection',
            name='voix_gagnant',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultatelection',
            name='voix_gagnant_precedent',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
