# Generated by Django 5.2 on 2025-05-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exploration', '0002_resultatelection_desir_changement_avec_centre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultatelection',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='resultatelection',
            table='legislative_per_cir',
        ),
    ]
