# Generated by Django 5.2 on 2025-05-01 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exploration', '0003_alter_resultatelection_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultatelection',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
